server:
  port: 8080

app:
  api:
    name: Cupon de Compra
    version: v1

spring:
#  datasource:
#    url: jdbc:postgresql://mypostgres:5432/coupon
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: 1qaz!QAZ
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:coupondb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ALWAYS

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs