server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:coupontest
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
